/**
 * Wrangler config generation. Replaces every hand-edited TOML: the operator edits ONE json file and
 * the configs are derived from it, deterministically. Same config in -> byte-identical TOML out.
 *
 * Invariants enforced here and re-checked by `assertEnvIsolation()`:
 *   - a STAGING consumer ALWAYS has a Service Binding to its own staging receiver and NO webhook
 *     secret: it is structurally unable to reach any other host (R4 hard-lock, unchanged);
 *   - a PROD config never contains a Service Binding, a staging name or the staging receiver;
 *   - no config ever contains a secret VALUE; secrets are declared in [secrets].required only.
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { names, slug, MANAGED_VAR, BUILD_VAR, managedValue, belongsTo } from './naming.mjs';
import { runtimeDestinations } from './config.mjs';
import { KawaError } from './log.mjs';

export const COMPAT_DATE = '2024-12-18';

const q = (s) => JSON.stringify(String(s));            // TOML basic string (JSON escapes are valid TOML)
function lit(s) {                                         // TOML literal string, used for the JSON var
  if (String(s).includes("'") || /[\r\n]/.test(s)) throw new Error('value cannot be a TOML literal string');
  return `'${s}'`;
}

function sha256(buf) { return crypto.createHash('sha256').update(buf).digest('hex'); }

/** Source files that make up each Worker's code, relative to edge/. */
export const SOURCES = {
  ingress: ['src/ingress-entry.js', 'src/producer.js', 'src/sequencer.js', 'src/destinations.js'],
  consumer: ['src/consumer-entry.js', 'src/consumer.js', 'src/destinations.js'],
  receiver: ['staging-receiver/src/index.js'],
  admin: ['admin-worker/src/index.js'],
};

export const MAIN = {
  ingress: 'src/ingress-entry.js',
  consumer: 'src/consumer-entry.js',
  receiver: 'staging-receiver/src/index.js',
  admin: 'admin-worker/src/index.js',
};

/** Build digest = config text (without the digest line) + the exact bytes of the Worker's sources. */
function withBuild(role, text, edgeDir) {
  const h = crypto.createHash('sha256');
  h.update(text);
  for (const f of SOURCES[role]) { h.update('\0' + f + '\0'); h.update(fs.readFileSync(path.join(edgeDir, f))); }
  const digest = h.digest('hex');
  return { text: text.replace('__BUILD__', digest), build: digest };
}

function header(env, role, extra = '') {
  return [
    `# GENERATED by the KAWA Edge deployer — DO NOT EDIT. Source: config/kawa-edge.json`,
    `# Environment: ${env.toUpperCase()} · role: ${role}${extra ? ' · ' + extra : ''}`,
    `# Deployed ONLY with an explicit --config pointing at this file.`,
  ].join('\n');
}

function mainPath(edgeDir, role) { return path.join(edgeDir, MAIN[role]); }

export function renderIngress(env, dests, edgeDir) {
  const lines = [
    header(env, 'ingress + EdgeSequencer Durable Object'),
    `name = ${q(names.ingress(env))}`,
    `main = ${q(mainPath(edgeDir, 'ingress'))}`,
    `compatibility_date = ${q(COMPAT_DATE)}`,
    `workers_dev = true`,
    `preview_urls = false`,
    '',
    '[exports.EdgeSequencer]',
    'type = "durable-object"',
    'storage = "sqlite"',
    '',
    '[[durable_objects.bindings]]',
    'name = "SEQUENCER"',
    'class_name = "EdgeSequencer"',
    '',
    '# NON-SECRET configuration only. The Sequencer is the authority on enabled/disabled.',
    '[vars]',
    `DESTINATIONS = ${lit(JSON.stringify(runtimeDestinations(dests)))}`,
    `${MANAGED_VAR} = ${q(managedValue(env, 'ingress'))}`,
    `${BUILD_VAR} = "__BUILD__"`,
    '',
    '# One queue per destination (enabled or not), so re-enabling never needs a new binding.',
  ];
  for (const d of dests) {
    lines.push('[[queues.producers]]', `queue = ${q(names.queue(env, d.id))}`, `binding = ${q(`DEST_${d.id}_QUEUE`)}`, '');
  }
  lines.push('[secrets]', 'required = ["WEBHOOK_PATH_TOKEN", "HALT_NOTIFY_URL"]', '');
  return withBuild('ingress', lines.join('\n'), edgeDir);
}

export function renderConsumer(env, dest, edgeDir) {
  const id = dest.id;
  const lines = [
    header(env, `delivery consumer for ${id}`),
    `name = ${q(names.consumer(env, id))}`,
    `main = ${q(mainPath(edgeDir, 'consumer'))}`,
    `compatibility_date = ${q(COMPAT_DATE)}`,
    '# A queue consumer needs no HTTP surface at all.',
    `workers_dev = false`,
    `preview_urls = false`,
    '',
    '[[durable_objects.bindings]]',
    'name = "SEQUENCER"',
    'class_name = "EdgeSequencer"',
    `script_name = ${q(names.ingress(env))}`,
    '',
    '[[queues.consumers]]',
    `queue = ${q(names.queue(env, id))}`,
    'max_batch_size = 1',
    'max_batch_timeout = 0',
    '# High: a message waiting its turn retries legitimately (R4). Deliberately NO dead_letter_queue:',
    '# FAILED_PERMANENT means a permanent 4xx from THIS Hub, written by the consumer itself.',
    'max_retries = 100',
    'max_concurrency = 1',
    '',
    '[[queues.producers]]',
    `queue = ${q(names.dlq(env, id))}`,
    `binding = ${q(`DEST_${id}_DLQ`)}`,
    '',
  ];
  if (env === 'staging') {
    lines.push(
      '# STAGING HARD-LOCK: delivery is bound to this destination\'s staging receiver. No other host is reachable.',
      '[[services]]',
      `binding = ${q(`DEST_${id}_FETCHER`)}`,
      `service = ${q(names.receiver(env, id))}`,
      '');
  }
  lines.push(
    '[vars]',
    `CONSUMER_DESTINATION_ID = ${q(id)}`,
    '# Only this destination\'s own entry: the consumer is pinned and never reads another one.',
    `DESTINATIONS = ${lit(JSON.stringify(runtimeDestinations([dest])))}`);
  if (env === 'staging') {
    lines.push('# Not a secret in STAGING: the Service Binding decides the target; this host is never dialled.',
               `DEST_${id}_WEBHOOK_URL = ${q(`https://staging-receiver.invalid/webhook/${slug(id)}-stg`)}`);
  }
  lines.push(`${MANAGED_VAR} = ${q(managedValue(env, `consumer:${id}`))}`, `${BUILD_VAR} = "__BUILD__"`, '');
  if (env === 'prod') {
    lines.push('# PROD: this destination\'s OWN webhook URL (path token included). Bound only here.',
               '[secrets]', `required = [${q(`DEST_${id}_WEBHOOK_URL`)}]`, '');
  }
  return withBuild('consumer', lines.join('\n'), edgeDir);
}

export function renderReceiver(dest, edgeDir) {
  const env = 'staging';
  const lines = [
    header(env, `staging receiver for ${dest.id}`, 'a KAWA stand-in with no ability to trade'),
    `name = ${q(names.receiver(env, dest.id))}`,
    `main = ${q(mainPath(edgeDir, 'receiver'))}`,
    `compatibility_date = ${q(COMPAT_DATE)}`,
    `workers_dev = true`,
    `preview_urls = false`,
    '',
    '[exports.ReceiverLedger]',
    'type = "durable-object"',
    'storage = "sqlite"',
    '',
    '[[durable_objects.bindings]]',
    'name = "LEDGER"',
    'class_name = "ReceiverLedger"',
    '',
    '[vars]',
    `${MANAGED_VAR} = ${q(managedValue(env, `receiver:${dest.id}`))}`,
    `${BUILD_VAR} = "__BUILD__"`,
    '',
    '[secrets]',
    'required = ["CONTROL_TOKEN"]',
    '',
  ];
  return withBuild('receiver', lines.join('\n'), edgeDir);
}

export function renderAdmin(edgeDir) {
  const env = 'staging';
  const lines = [
    header(env, 'temporary admin (gates I/J)', 'NEVER deployed to PROD (R4)'),
    `name = ${q(names.admin(env))}`,
    `main = ${q(mainPath(edgeDir, 'admin'))}`,
    `compatibility_date = ${q(COMPAT_DATE)}`,
    `workers_dev = true`,
    `preview_urls = false`,
    '',
    '[[durable_objects.bindings]]',
    'name = "SEQUENCER"',
    'class_name = "EdgeSequencer"',
    `script_name = ${q(names.ingress(env))}`,
    '',
    '[vars]',
    `${MANAGED_VAR} = ${q(managedValue(env, 'admin'))}`,
    `${BUILD_VAR} = "__BUILD__"`,
    '',
    '[secrets]',
    'required = ["ADMIN_TOKEN"]',
    '',
  ];
  return withBuild('admin', lines.join('\n'), edgeDir);
}

/**
 * Every Worker of one environment, in deployment order. `role` drives which secrets it needs.
 * STAGING: receivers -> ingress -> consumers -> admin.  PROD: ingress -> consumers.
 */
export function renderEnv(env, dests, edgeDir) {
  const workers = [];
  if (env === 'staging') {
    for (const d of dests) workers.push({ role: 'receiver', dest: d.id, name: names.receiver(env, d.id), ...renderReceiver(d, edgeDir) });
  }
  workers.push({ role: 'ingress', name: names.ingress(env), ...renderIngress(env, dests, edgeDir) });
  for (const d of dests) workers.push({ role: 'consumer', dest: d.id, name: names.consumer(env, d.id), ...renderConsumer(env, d, edgeDir) });
  if (env === 'staging') workers.push({ role: 'admin', name: names.admin(env), ...renderAdmin(edgeDir) });
  const queues = [];
  for (const d of dests) {
    queues.push({ name: names.queue(env, d.id), kind: 'main', dest: d.id });
    queues.push({ name: names.dlq(env, d.id), kind: 'dlq', dest: d.id });
  }
  const plan = { env, workers, queues };
  assertEnvIsolation(plan);
  return plan;
}

/** Refuse any plan that could let one environment reach the other. Checked on every render. */
export function assertEnvIsolation(plan) {
  const { env } = plan;
  const bad = (msg) => { throw new KawaError('ENV_ISOLATION_VIOLATION', `${env.toUpperCase()} plan refused: ${msg}`); };
  for (const r of [...plan.workers, ...plan.queues]) if (!belongsTo(env, r.name)) bad(`resource ${r.name} does not belong to ${env}`);
  for (const w of plan.workers) {
    const t = w.text;
    if (/integrademia/i.test(t) && env === 'staging') bad(`${w.name} mentions a production hostname`);
    if (/:(8180|8080)\b/.test(t)) bad(`${w.name} names a forbidden control port`);
    if (env === 'prod') {
      if (/\[\[services\]\]/.test(t)) bad(`${w.name} has a Service Binding (staging hard-lock shape)`);
      if (/-stg"|staging-receiver/.test(t)) bad(`${w.name} references a STAGING resource`);
    }
    if (env === 'staging' && w.role === 'consumer') {
      if (!new RegExp(`service = "${names.receiver(env, w.dest)}"`).test(t)) bad(`${w.name} is not hard-locked to its staging receiver`);
      if (/\[secrets\]/.test(t)) bad(`${w.name} declares a webhook secret`);
    }
  }
  return true;
}

export function writeBuild(plan, buildDir) {
  const dir = path.join(buildDir, plan.env);
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
  for (const w of plan.workers) {
    w.configPath = path.join(dir, `${w.name}.toml`);
    fs.writeFileSync(w.configPath, w.text);
  }
  return dir;
}

/** Digest of the Edge runtime code (ingress + consumer). Binds STAGING evidence to what PROD runs. */
export function edgeSourcesHash(edgeDir) {
  const h = crypto.createHash('sha256');
  for (const f of [...new Set([...SOURCES.ingress, ...SOURCES.consumer])].sort()) {
    h.update(f + '\0'); h.update(fs.readFileSync(path.join(edgeDir, f)));
  }
  return h.digest('hex');
}
